<?php
ob_start();
include("../session.php");
include("../dbcon/config.php");
include("../dbcon/pdocon.php");
include("apps/view/header.html");
include("apps/view/dashboard.html");
include("apps/view/footer.html");
?>